### ISSUE TITLE
[BUG]  CLI seems to require PR when I am testing against file.

### ISSUE THREAD

**Issue by Merovex** [JasonEtco/todo#272]
**Describe the bug**

When I try to run  the CLI to target a file per the documentation (`./bin/todo.js -o <redacted> -r <redacted> -f src/<redacted>`), I get an error message asserting I am missing the PR

**To Reproduce**

```
./bin/todo.js -o <redacted> -r <redacted> -f src/<redacted>
RequestError [HttpError]: Empty value for parameter 'pull_number': undefined
    at /Users/<redacted>/todo/node_modules/@octokit/rest/plugins/validate/validate.js:74:15
    at Array.forEach (<anonymous>)
    at /Users/<redacted>/node_modules/@octokit/rest/plugins/validate/validate.js:42:12
    at Array.forEach (<anonymous>)
    at validate (/Users/<redacted>s/todo/node_modules/@octokit/rest/plugins/validate/validate.js:15:23)
    at async Job.doExecute (/Users/<redacted>/todo/node_modules/bottleneck/light.js:405:18) {
  name: 'HttpError',
  status: 400,
  headers: {},
  request: {
    method: 'GET',
    baseUrl: 'https://api.github.com',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.36.0 Node.js/12.14.1 (macOS Catalina; x64)'
    },
    mediaType: { format: '', previews: [] },
    request: {
      hook: [Function: bound bound register],
      validate: [Object],
      retryCount: 1
    },
    url: '/repos/:owner/:repo/pulls/:pull_number',
    owner: '<redacted>',
    repo: '<redacted>',
    pull_number: undefined
  }
}
```

**Expected behavior**

Expected it to work against the file per the documentation.

**Additional context**

Installed per documentation, then immediately ran this test. I was doing this since it was not creating an issue when pushing changes to the repo. I wanted to see where the hangup lay.

**Comment by Merovex** [comment]
No longer relevant since the author failed to respond. I wrote my own solution
